//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bsensor
{
    using System;
    using System.Collections.Generic;
    
    public partial class bike_power
    {
        public int id { get; set; }
        public int coord_id { get; set; }
        public int num_calc_power { get; set; }
        public double avg_calc_power { get; set; }
        public double ssd_calc_power { get; set; }
        public int num_calc_torque { get; set; }
        public double avg_calc_torque { get; set; }
        public double ssd_calc_torque { get; set; }
        public int num_calc_crank_cadence { get; set; }
        public double avg_calc_crank_cadence { get; set; }
        public double ssd_calc_crank_cadence { get; set; }
        public int num_calc_wheel_speed { get; set; }
        public double avg_calc_wheel_speed { get; set; }
        public double ssd_calc_wheel_speed { get; set; }
        public int num_calc_wheel_distance { get; set; }
        public double avg_calc_wheel_distance { get; set; }
        public double ssd_calc_wheel_distance { get; set; }
    }
}
