//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bsensor
{
    using System;
    using System.Collections.Generic;
    
    public partial class heart_rate
    {
        public int id { get; set; }
        public int coord_id { get; set; }
        public int num_s { get; set; }
        public double avg_s { get; set; }
        public double ssd_s { get; set; }
    }
}
