//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bsensor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BsensorContext : DbContext
    {
        public BsensorContext()
            : base("name=BsensorContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bike_power> bike_power { get; set; }
        public virtual DbSet<coord> coords { get; set; }
        public virtual DbSet<heart_rate> heart_rate { get; set; }
        public virtual DbSet<s_sensor_readings> s_sensor_readings { get; set; }
        public virtual DbSet<sensor_types> sensor_types { get; set; }
        public virtual DbSet<sensor> sensors { get; set; }
        public virtual DbSet<shimmer_ecg_readings> shimmer_ecg_readings { get; set; }
        public virtual DbSet<shimmer_emg_readings> shimmer_emg_readings { get; set; }
        public virtual DbSet<shimmer_sensor_readings> shimmer_sensor_readings { get; set; }
        public virtual DbSet<shimmer_sensor_types> shimmer_sensor_types { get; set; }
        public virtual DbSet<shimmer_sensors> shimmer_sensors { get; set; }
        public virtual DbSet<trip> trips { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<v_sensor_readings> v_sensor_readings { get; set; }
        public virtual DbSet<shimmer_configs> shimmer_configs { get; set; }
    }
}
