//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bsensor
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_sensor_readings
    {
        public int id { get; set; }
        public Nullable<long> coord_id { get; set; }
        public Nullable<int> sensor_id { get; set; }
        public Nullable<int> num_readings { get; set; }
        public Nullable<double> avg_s { get; set; }
        public Nullable<double> ssd_s { get; set; }
    }
}
