//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bsensor
{
    using System;
    using System.Collections.Generic;
    
    public partial class shimmer_configs
    {
        public int sc_trip_id { get; set; }
        public string sc_bluetooth_id { get; set; }
        public double sc_sampling_rate { get; set; }
        public int sc_accel_range { get; set; }
        public int sc_gsr_range { get; set; }
        public double sc_battery_limit { get; set; }
        public int sc_int_exp_power { get; set; }
        public int sc_low_pwr_mag { get; set; }
        public int sc_low_pwr_accel { get; set; }
        public int sc_gyro { get; set; }
        public int sc_5v_reg { get; set; }
        public int sc_gyro_range { get; set; }
        public int sc_mag_range { get; set; }
        public int sc_pressure_range { get; set; }
        public int sc_ref_electrode { get; set; }
        public int sc_lead_off_detection { get; set; }
        public int sc_lead_off_current { get; set; }
        public int sc_lead_off_comparator { get; set; }
        public int sc_exg_gain { get; set; }
        public int sc_exg_res { get; set; }
    }
}
