//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bsensor
{
    using System;
    using System.Collections.Generic;
    
    public partial class shimmer_ecg_readings
    {
        public int id { get; set; }
        public int coord_id { get; set; }
        public int shimmer_sensor_id { get; set; }
        public float timestamp { get; set; }
        public double exg1_ch1 { get; set; }
        public double exg1_ch2 { get; set; }
        public double exg2_ch1 { get; set; }
        public double exg2_ch2 { get; set; }
    }
}
