//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bsensor
{
    using System;
    using System.Collections.Generic;
    
    public partial class shimmer_sensor_readings
    {
        public long id { get; set; }
        public Nullable<long> coord_id { get; set; }
        public Nullable<int> shimmer_sensor_id { get; set; }
        public Nullable<long> num_s { get; set; }
        public Nullable<double> avg_0 { get; set; }
        public Nullable<double> avg_1 { get; set; }
        public Nullable<double> avg_2 { get; set; }
        public Nullable<double> std_0 { get; set; }
        public Nullable<double> std_1 { get; set; }
        public Nullable<double> std_2 { get; set; }
    }
}
