//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bsensor
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string app_version { get; set; }
        public System.DateTime created { get; set; }
        public string device { get; set; }
        public string deviceModel { get; set; }
        public long id { get; set; }
    }
}
