//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bsensor
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sensor_readings
    {
        public long id { get; set; }
        public Nullable<long> coord_id { get; set; }
        public Nullable<int> sensor_id { get; set; }
        public Nullable<long> num_s { get; set; }
        public Nullable<double> avg_x { get; set; }
        public Nullable<double> avg_y { get; set; }
        public Nullable<double> avg_z { get; set; }
        public Nullable<double> ssd_x { get; set; }
        public Nullable<double> ssd_y { get; set; }
        public Nullable<double> ssd_z { get; set; }
    }
}
